# Generated by Django 5.2 on 2025-06-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Compliant', 'Compliant'), ('Pending Review', 'Pending Review'), ('Require Attention', 'Require Attention')], default='Pending Review', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('last_audit_date', models.DateTimeField(blank=True, null=True)),
                ('next_audit_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='compliance_documents/')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Require Attention', 'Require Attention')], default='In Progress', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='hospitals.hospital')),
                ('Compliance_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.compliancestandard')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audit_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('auditor', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='hospitals.hospital')),
                ('Compliance_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.compliancestandard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='compliancestandard',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_compliance_report_per_hospital'),
        ),
    ]
