# Generated by Django 5.2 on 2025-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('employees', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('tickets', '0003_alter_ticket_assigned_to_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('hospital', 'ticket_id'), name='unique Ticket name per hospital'),
        ),
    ]
