# Generated by Django 5.1.7 on 2025-04-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff'), ('engineer', 'Engineer'), ('receptionist', 'Receptionist'), ('other', 'Other')], default='staff', max_length=50)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('emergency', 'Emergency'), ('it', 'IT'), ('administration', 'Administration')], default='it', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('access_level', models.CharField(choices=[('admin', 'Administrator'), ('full', 'Full Access'), ('standard', 'Standard Access'), ('limited', 'Limited Access'), ('none', 'No Access')], default='standard', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
