# Generated by Django 5.2 on 2025-06-17 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('hospital', 'employee_id'), name='unique_employee_per_hospital'),
        ),
    ]
