# Generated by Django 5.2 on 2025-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nfc_uuid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
