# Generated by Django 5.2 on 2025-04-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('inventory', '0003_alter_category_name_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('hospital', 'name', 'tax_id')},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(blank=True, to='inventory.category'),
        ),
    ]
