# Generated by Django 5.2 on 2025-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
